GET http://localhost:5000/

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "ok2@ok.com",
    "password": "OKOKOK",
    "firstname": "OK"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ok2@ok.com",
    "password": "OKOKOK"
}