###
POST http://localhost:3000/sendMail/validationAccountLink
Content-Type: application/json

{
    "mailTo": "nelob60708@anlubi.com",
    "confirmationCode": "token1234",
    "firstName": "Nils"
}

###
GET http://localhost:3000/sendMail/confirm/token1234
Content-Type: application/json