###
POST http://localhost:3000/validationAccountLink
Content-Type: application/json

{
    "mailTo": "jedojes450@anlubi.com",
    "confirmationCode": "b5ae3000-08ba-4919-8023-4d78ccba39e3",
    "firstName": "Océ"
}

###
GET http://localhost:3000/sendMail/confirm/token1234
Content-Type: application/json

###
POST http://localhost:3000/password-reset
Content-Type: application/json

{
    "email": "meyox97193@altpano.com"
}

###
POST http://localhost:3000/password-reset/77/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzcsImlhdCI6MTY1ODY4NzgxMiwiZXhwIjoxNjkwMjQ1NDEyfQ.mardcMNytIcSuRfxz44u7Qnv3dMsEBoXKX29_YdTJ2E
Content-Type: application/json

{
    "password": "nouveau mdp zeffezezfefzfezezzf"
}


###
GET http://localhost:3000/confirm/b5ae3000-08ba-4919-8023-4d78ccba39e3
Content-Type: application/json